export const dailyPanel = `
<section class="panel" id="todayPanel"><div style="display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap"><div><h2>Pendiente de hoy</h2><p class="panel-desc">Lo que necesita atención, con la acción a mano.</p></div><button class="btn btn-ghost" id="reloadToday">Actualizar</button></div><div id="todayTasks" aria-live="polite">Cargando pendientes…</div><p id="dailyError" role="alert" style="color:var(--danger)"></p></section>
<section class="panel"><h2>Buscar paciente</h2><form id="patientSearchForm" style="display:flex;gap:10px;flex-wrap:wrap;margin-top:14px"><label style="flex:1;min-width:160px">Nombre o teléfono<input id="patientSearch" type="search" minlength="2" maxlength="80" placeholder="Escribe al menos 2 caracteres" style="display:block;width:100%;padding:12px;border:1px solid var(--border);border-radius:8px;background:var(--surface);color:var(--text-primary)"></label><button class="btn btn-primary">Buscar</button></form><div id="patientResults" aria-live="polite"></div><div id="sharingLink" hidden></div></section>
`;
export const dailyScript = String.raw`
(()=>{
const byId=id=>document.getElementById(id);const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=a=>'/simulator/operations?appointment='+encodeURIComponent(a);
async function call(path,body){const r=await fetch('/simulator/api/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'No se pudo completar. Actualiza la página.');return d;}
const row=(title,detail,actions)=>'<div style="padding:14px 0;border-bottom:1px solid var(--border);display:flex;justify-content:space-between;gap:14px;flex-wrap:wrap"><div><strong>'+safe(title)+'</strong><p style="margin:5px 0;color:var(--text-secondary)">'+safe(detail)+'</p></div><div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap">'+actions+'</div></div>';
const btn=(text,path)=>'<button class="btn btn-ghost" data-daily-action="'+safe(path)+'">'+text+'</button>';
async function load(){try{const d=await call('today');byId('todayTasks').innerHTML=d.appointments.map(a=>row(a.when+' · '+a.patientName,a.serviceLabel+' · '+a.statusLabel,(a.status==='PENDING_CONFIRMATION'?btn('Confirmar','appointments/'+a.id+'/confirm'):'')+(a.status==='ARRIVED'?'<a class="btn btn-primary" href="'+link(a.id)+'">Registrar atención</a>':'<button class="btn btn-ghost" data-arrived="'+safe(a.id)+'">Ha llegado</button>')+'<a class="btn btn-ghost" href="'+link(a.id)+'">Abrir cita</a>')).join('')+(d.handoffs?row('Conversaciones que necesitan atención',d.handoffs+' pendientes','<a class="btn btn-primary" href="/simulator/operations#handoffs">Atender</a>'):'')+d.requests.map(r=>row(r.name+' · '+r.phone,r.message,'<a class="btn btn-ghost" href="tel:+'+safe(r.phone)+'">Llamar</a>'+btn('Marcar atendida','contacts/'+r.id+'/resolve'))).join('')+d.failures.map(f=>row(f.label,'Comprueba la cita y contacta con el paciente si hace falta. No se reenvía automáticamente.',(f.appointmentId?'<a class="btn btn-ghost" href="'+link(f.appointmentId)+'">Abrir cita</a>':'')+btn('Ya lo he revisado','jobs/'+f.id+'/review'))).join('')+(d.inbox?row('Mensajes sin resolver',d.inbox+' mensajes necesitan revisión','<a class="btn btn-ghost" href="/simulator/operations#failures">Revisar mensajes</a>'):'')+d.portal.map(p=>row('Solicitud web pendiente de revisar',p.contactName+' · '+p.contactPhone+' · Comprueba la agenda antes de repetirla.',btn('Ya lo he revisado','portal/'+p.tokenHash+'/review'))).join('');if(!byId('todayTasks').innerHTML)byId('todayTasks').innerHTML='<p class="muted">Todo al día. No hay tareas pendientes para hoy.</p>';byId('dailyError').textContent='';}catch(e){byId('dailyError').textContent=e.message;}}
byId('reloadToday').onclick=load;window.addEventListener('clinic-agenda-changed',load);
byId('todayTasks').onclick=async e=>{const b=e.target.closest('button');if(!b)return;b.disabled=true;try{if(b.dataset.dailyAction)await call(b.dataset.dailyAction,{});if(b.dataset.arrived)await call('appointments/'+b.dataset.arrived+'/attendance',{status:'ARRIVED'});await load();window.dispatchEvent(new Event('clinic-daily-changed'));}catch(err){byId('dailyError').textContent=err.message;b.disabled=false;}};
let searchVersion=0;
byId('patientSearchForm').onsubmit=async e=>{e.preventDefault();const q=byId('patientSearch').value.trim();if(q.length<2)return;const version=++searchVersion;byId('patientResults').textContent='Buscando…';try{const d=await call('patients/search?q='+encodeURIComponent(q));if(version!==searchVersion)return;byId('patientResults').innerHTML=d.patients.map(p=>row(p.name,p.phone+(p.next?' · '+p.next.when+' · '+p.next.serviceLabel:' · Sin próxima cita'),(p.next?'<a class="btn btn-primary" href="'+link(p.next.id)+'">Cambiar cita</a><button class="btn btn-ghost" data-share="'+safe(p.next.id)+'">Enlace del paciente</button>':'')+'<a class="btn btn-ghost" href="/simulator/operations?patient='+encodeURIComponent(p.id)+'">Nueva cita</a>')).join('')||'<p class="muted">No encontramos pacientes con ese nombre o teléfono.</p>';}catch(err){byId('patientResults').textContent=err.message;}};
byId('patientResults').onclick=async e=>{const b=e.target.closest('[data-share]');if(!b)return;if(!await confirmDialog('Se generará un enlace privado y dejarán de funcionar los enlaces anteriores de esta cita. Compártelo solo con el paciente.','Generar enlace'))return;b.disabled=true;try{const d=await call('appointments/'+b.dataset.share+'/link',{});const box=byId('sharingLink');box.hidden=false;box.innerHTML='<p>Enlace privado de la cita. Selecciona y copia para compartir con el paciente:</p><input aria-label="Enlace privado de la cita" readonly style="width:100%;padding:12px" value="'+safe(location.origin+'/reservar#'+d.token)+'">';box.querySelector('input').select();}catch(err){byId('dailyError').textContent=err.message;}finally{b.disabled=false;}};
load();
})();
`;
