import { pageShell, ClinicBranding } from "./layout";
import { DateTime } from "luxon";
import { clinicConfig } from "../config";
export function renderOperationsPage(clinic: ClinicBranding) {
  return pageShell({ active: "operations", clinic, brand: clinic.brandColor, title: "Recepción", extraStyles: `
    .operations{max-width:1200px;margin:auto}.toolbar,.actions{display:flex;gap:10px;flex-wrap:wrap;align-items:center}.toolbar{justify-content:space-between;margin-bottom:20px}label{display:flex;flex-direction:column;gap:5px;font-size:13px}input,select,textarea{background:var(--surface);color:var(--text-primary);border:1px solid var(--border-strong);border-radius:8px;padding:10px;font:inherit;max-width:100%;box-sizing:border-box}input:focus-visible,select:focus-visible,textarea:focus-visible{outline:2px solid var(--brand)}.form-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin:16px 0}.agenda-item{display:grid;grid-template-columns:90px 1fr;gap:16px;padding:18px 0;border-bottom:1px solid var(--border)}.agenda-item h3{margin:0 0 5px}.agenda-item p{margin:5px 0 12px}.pending-review{color:var(--warning)}.conversation{border-bottom:1px solid var(--border);padding:20px 0}.messages{max-height:240px;overflow:auto;background:var(--surface-subtle);padding:12px;border-radius:8px;margin:12px 0;white-space:pre-wrap}.messages p{margin:8px 0}.error{color:var(--danger)}.kpi-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}.kpi-grid strong{font-size:25px;display:block;margin:8px 0}.hint{font-size:12px;color:var(--text-secondary)}button{min-height:40px}.hidden{display:none}@media(max-width:700px){.form-grid,.kpi-grid{grid-template-columns:1fr 1fr}.agenda-item{grid-template-columns:1fr}.operations h1{font-size:26px}}@media(max-width:420px){.form-grid{grid-template-columns:1fr}.toolbar{align-items:stretch}}
  `, bodyHtml: `<div class="operations">
    <div class="toolbar"><div><h1>Recepción</h1><p class="muted">Agenda, asistencia y conversaciones del centro</p></div><button class="btn btn-ghost" id="logout">Cerrar sesión</button></div>
    <section class="panel"><div class="toolbar"><h2>Resultados</h2><label>Periodo<select id="period"><option value="month">Este mes</option><option value="week">Esta semana</option><option value="all">Todo el historial</option></select></label></div><div id="metrics" class="kpi-grid"></div><p class="hint">Las cifras corresponden a la fecha de la cita. Los cobros son importes registrados por recepción; no se procesan pagos.</p></section>
    <section class="panel"><div class="toolbar"><h2>Agenda del día</h2><div class="actions"><label>Día<input id="day" type="date"></label><label>Profesional<select id="professional"><option value="">Todos</option></select></label><button id="refresh" class="btn btn-ghost">Actualizar</button></div></div><div id="agenda" aria-live="polite">Cargando agenda…</div></section>
    <section class="panel"><h2>Nueva cita o cambio de cita</h2><p class="panel-desc">Pulsa «Cambiar» en una cita para conservarla hasta que el nuevo horario esté reservado.</p><form id="booking"><div class="form-grid"><label>Nombre<input name="name" required maxlength="80"></label><label>Teléfono<input name="phone" required placeholder="34600111222" pattern="[0-9]{7,15}"></label><label>Servicio<select name="serviceId" required></select></label><label>Profesional<select name="professionalId" required></select></label><label>Fecha y hora<input name="startsAt" type="datetime-local" required></label></div><div class="actions"><button class="btn btn-primary" id="saveBooking">Crear cita</button><button type="button" id="cancelEdit" class="btn btn-ghost hidden">Dejar de cambiar</button></div></form></section>
    <section class="panel"><h2>Ausencias y descansos</h2><p class="panel-desc">Los bloqueos se reflejan también en los horarios que ofrece el asistente.</p><form id="block"><div class="form-grid"><label>Profesional<select name="professionalId"><option value="">Todo el centro</option></select></label><label>Desde<input name="startsAt" type="datetime-local" required></label><label>Hasta<input name="endsAt" type="datetime-local" required></label><label>Motivo<input name="reason" required maxlength="120" placeholder="Vacaciones, descanso…"></label></div><button class="btn btn-primary">Bloquear tramo</button></form><div id="blocks"></div></section>
    <section class="panel"><h2>Atención humana</h2><p class="panel-desc">Hazte cargo de una conversación para responder. El asistente permanece pausado hasta que la devuelvas.</p><div id="handoffs" aria-live="polite"></div></section>
    <section id="teamPanel" class="panel hidden"><h2>Equipo y copias de seguridad</h2><form id="staff"><div class="form-grid"><label>Correo<input name="email" type="email" required></label><label>Contraseña inicial<input name="password" type="password" minlength="12" maxlength="256" required autocomplete="new-password"></label><label>Permisos<select name="role"><option value="RECEPTION">Recepción</option><option value="ADMIN">Administrador</option></select></label></div><button class="btn btn-primary">Crear usuario</button></form><div id="staffList"></div><button id="backup" class="btn btn-ghost">Crear copia de seguridad</button><p class="hint">También se crea una copia diaria. Guarda las copias en almacenamiento protegido.</p></section>
    <section class="panel"><h2>Mensajes que necesitan revisión</h2><div id="failures"></div></section>
    <p class="error" id="pageError" role="alert"></p>
  </div>`, bodyScript: `
  const el=id=>document.getElementById(id); let state, editing=null;
  const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const euro=v=>Number(v).toLocaleString('es-ES',{style:'currency',currency:'EUR'});
  async function api(url,body){const r=await fetch('/simulator/api/'+url,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'No se pudo completar la acción.');return d;}
  async function act(fn){try{el('pageError').textContent='';await fn();await load();toast('Cambio guardado');}catch(e){el('pageError').textContent=e.message;toast(e.message,'error');}}
  function options(pros){return pros.map(p=>'<option value="'+esc(p.id)+'">'+esc(p.name)+'</option>').join('');}
  function servicePros(){const id=el('booking').elements.serviceId.value;const pros=state.professionals.filter(p=>p.serviceIds.includes(id));el('booking').elements.professionalId.innerHTML=options(pros);el('saveBooking').disabled=!pros.length;}
  async function load(){
    state=await api('operations?date='+encodeURIComponent(el('day').value)+'&professionalId='+encodeURIComponent(el('professional').value)+'&period='+el('period').value);
    const current=el('professional').value;el('professional').innerHTML='<option value="">Todos</option>'+options(state.professionals);el('professional').value=current;
    el('block').elements.professionalId.innerHTML='<option value="">Todo el centro</option>'+options(state.professionals);
    const service=el('booking').elements.serviceId.value;el('booking').elements.serviceId.innerHTML=state.services.map(s=>'<option value="'+esc(s.id)+'">'+esc(s.label)+'</option>').join('');if(service)el('booking').elements.serviceId.value=service;const pro=el('booking').elements.professionalId.value;servicePros();if(pro)el('booking').elements.professionalId.value=pro;
    const m=state.stats;el('metrics').innerHTML=[['Valor de reservas recuperadas',euro(m.recoveredRevenueEur)],['Recuperadas atendidas',m.recoveredAttended],['Valor de citas atendidas',euro(m.recoveredAttendedValueEur)],['Cobros recuperados registrados',euro(m.recoveredPaidEur)]].map(x=>'<div><span class="muted">'+x[0]+'</span><strong>'+x[1]+'</strong></div>').join('');
    el('agenda').innerHTML=state.appointments.map(a=>{const active=['PENDING_CONFIRMATION','CONFIRMED'].includes(a.status);return '<article class="agenda-item"><strong>'+esc(a.time)+'</strong><div><h3>'+esc(a.patient.name||a.patient.phone)+' · '+esc(a.serviceLabel)+'</h3><p class="muted">'+esc(a.professional?a.professional.name:'Sin profesional')+' · '+esc(a.statusLabel)+'</p>'+(a.needsReview?'<p class="pending-review">Pendiente de registrar asistencia</p>':'')+'<div class="actions">'+(active?'<button class="btn btn-ghost" data-status="ARRIVED" data-id="'+a.id+'">Ha llegado</button><button class="btn btn-ghost" data-edit="'+a.id+'">Cambiar</button><button class="btn btn-danger-ghost" data-cancel="'+a.id+'">Cancelar</button>':'')+(['PENDING_CONFIRMATION','CONFIRMED','ARRIVED'].includes(a.status)?'<button class="btn btn-ghost" data-status="COMPLETED" data-id="'+a.id+'">Completada</button>':'')+(active&&a.needsReview?'<button class="btn btn-danger-ghost" data-status="NO_SHOW" data-id="'+a.id+'">No ha acudido</button>':'')+(a.status==='COMPLETED'?'<label>Cobrado (€)<input type="number" min="0" step="0.01" value="'+a.paidCents/100+'" id="pay-'+a.id+'"></label><button class="btn btn-ghost" data-pay="'+a.id+'">Guardar cobro</button>':'')+'</div></div></article>';}).join('')||'<p class="muted">No hay citas para este día.</p>';
    el('blocks').innerHTML=state.blocks.map(b=>'<p>'+esc(b.label)+' · '+esc(b.reason)+' <button class="btn btn-danger-ghost" data-unblock="'+b.id+'">Quitar bloqueo</button></p>').join('')||'<p class="muted">Sin bloqueos para este día.</p>';
    el('handoffs').innerHTML=state.handoffs.map(p=>'<article class="conversation"><h3>'+esc(p.name||p.phone)+'</h3><p>'+esc(p.handoffReason||'Solicita atención del equipo')+'</p><p class="hint">'+(p.handoffClaimedBy?'Asignada a '+esc(p.staffName):'Pendiente de asignar')+'</p><div class="messages">'+p.messages.map(m=>'<p><strong>'+(m.role==='user'?'Paciente':'Centro')+':</strong> '+esc(m.content)+'</p>').join('')+'</div><div class="actions"><button class="btn btn-ghost" data-claim="'+p.id+'">Hacerme cargo</button><button class="btn btn-ghost" data-resume="'+p.id+'">Devolver al asistente</button></div><form data-reply="'+p.id+'"><label>Respuesta<textarea name="text" required maxlength="4000" '+(p.handoffClaimedBy===state.staff.id?'':'disabled')+'></textarea></label><button class="btn btn-primary" '+(p.handoffClaimedBy===state.staff.id?'':'disabled')+'>Enviar respuesta</button></form></article>').join('')||'<p class="muted">No hay conversaciones pendientes.</p>';
    el('logout').classList.toggle('hidden',state.staff.id==='local-demo');el('teamPanel').classList.toggle('hidden',state.staff.role!=='ADMIN');if(!state.users.length)el('staff').elements.role.value='ADMIN';el('staffList').innerHTML=state.users.map(u=>'<p>'+esc(u.email)+' · '+esc(u.role)+' · '+(u.active?'Activo':'Inactivo')+(u.active&&u.id!==state.staff.id?' <button class="btn btn-danger-ghost" data-disable-user="'+u.id+'">Desactivar</button>':'')+'</p>').join('');
    el('failures').innerHTML=state.failures.map(f=>'<p>'+esc(f.phone)+' · '+esc(f.lastError)+' <button class="btn btn-ghost" data-dismiss="'+esc(f.id)+'">Marcar revisado</button></p>').join('')||'<p class="muted">Sin mensajes pendientes de revisión.</p>';
  }
  document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
    if(b.dataset.status)act(()=>api('appointments/'+b.dataset.id+'/attendance',{status:b.dataset.status}));
    if(b.dataset.cancel)act(async()=>{if(await confirmDialog('¿Cancelar esta cita y ofrecer el hueco a la lista de espera?','Cancelar cita'))await api('appointments/'+b.dataset.cancel+'/cancel',{});});
    if(b.dataset.pay)act(()=>api('appointments/'+b.dataset.pay+'/payment',{paidCents:Math.round(Number(el('pay-'+b.dataset.pay).value)*100)}));
    if(b.dataset.unblock)act(()=>api('blocks/'+b.dataset.unblock+'/remove',{}));
    if(b.dataset.claim)act(()=>api('handoffs/'+b.dataset.claim,{paused:true}));
    if(b.dataset.resume)act(()=>api('handoffs/'+b.dataset.resume,{paused:false}));
    if(b.dataset.disableUser)act(()=>api('staff/'+b.dataset.disableUser+'/disable',{}));
    if(b.dataset.dismiss)act(()=>api('inbox/'+b.dataset.dismiss+'/dismiss',{}));
    if(b.dataset.edit){const a=state.appointments.find(a=>a.id===b.dataset.edit);editing=a;const f=el('booking').elements;f.name.value=a.patient.name||'';f.phone.value=a.patient.phone;f.name.disabled=true;f.phone.disabled=true;f.serviceId.value=a.service;servicePros();f.professionalId.value=a.professionalId;f.startsAt.value=a.localStart;el('saveBooking').textContent='Guardar cambio';el('cancelEdit').classList.remove('hidden');el('booking').scrollIntoView({behavior:'smooth'});}
  });
  document.addEventListener('submit',e=>{if(e.target.dataset.reply){e.preventDefault();const text=e.target.elements.text.value;act(()=>api('handoffs/'+e.target.dataset.reply+'/reply',{text}));}});
  el('booking').addEventListener('submit',e=>{e.preventDefault();const f=e.target.elements;const body={name:f.name.value,phone:f.phone.value,serviceId:f.serviceId.value,professionalId:f.professionalId.value,startsAt:f.startsAt.value};act(async()=>{await api(editing?'appointments/'+editing.id+'/reschedule':'appointments',body);editing=null;e.target.reset();f.name.disabled=false;f.phone.disabled=false;el('saveBooking').textContent='Crear cita';el('cancelEdit').classList.add('hidden');});});
  el('cancelEdit').onclick=()=>{editing=null;el('booking').reset();el('booking').elements.name.disabled=false;el('booking').elements.phone.disabled=false;el('saveBooking').textContent='Crear cita';el('cancelEdit').classList.add('hidden');servicePros();};
  el('booking').elements.serviceId.onchange=servicePros;
  el('block').onsubmit=e=>{e.preventDefault();act(async()=>{await api('blocks',Object.fromEntries(new FormData(e.target)));e.target.reset();});};
  el('staff').onsubmit=e=>{e.preventDefault();act(async()=>{await api('staff',Object.fromEntries(new FormData(e.target)));e.target.reset();});};
  el('backup').onclick=()=>act(()=>api('backup',{}));el('logout').onclick=async()=>{await api('logout',{});location.href='/auth/login';};
  ['day','professional','period'].forEach(id=>el(id).onchange=()=>load().catch(e=>el('pageError').textContent=e.message));el('refresh').onclick=()=>load().catch(e=>el('pageError').textContent=e.message);
  el('day').value=${JSON.stringify(DateTime.now().setZone(clinicConfig.timezone).toISODate())};load().catch(e=>el('pageError').textContent=e.message);
  ` });
}
