// Kept separate from the HTML to make the patient flow easy to review.
export const patientScript = String.raw`
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(n);
const freshToken=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),v=>v.toString(16).padStart(2,'0')).join('');
const dateFormat=new Intl.DateTimeFormat('en-CA',{timeZone:data.timezone,year:'numeric',month:'2-digit',day:'2-digit'});
const today=dateFormat.format(new Date());const maxDate=dateFormat.format(new Date(Date.now()+59*86400000));
let step=0,service=null,professional=null,day=today,slot=null,mode='booking',access='',appointment=null,slotsVersion=0;
let formValues={name:'',phone:''};let requestToken=freshToken();const content=$('content');
async function api(path,body,key=''){
 const headers={'X-Patient-Request':'1'};if(key)headers.Authorization='Bearer '+key;
 if(body!==undefined)headers['Content-Type']='application/json';
 const res=await fetch('/reservar/api/'+path,{method:body===undefined?'GET':'POST',headers,body:body===undefined?undefined:JSON.stringify(body)});
 const d=await res.json();if(!res.ok)throw Error(d.error||'No se ha podido completar la solicitud.');return d;
}
function error(message){const box=$('error');if(box){box.textContent=message;box.focus();}}
function summary(){return '<div class="summary"><strong>'+esc(service?.label||appointment?.serviceLabel)+'</strong><br>'+esc(professional?.name||appointment?.professionalName)+(slot?' · '+esc(day)+' · '+esc(slot.label):'')+'</div>';}
function footer(){return '<p id="error" class="error" tabindex="-1" role="alert"></p>';}
function buttons(next,disabled=false){return '<div class="actions"><button type="button" class="back" id="back">← Volver</button><button class="primary" id="next" '+(disabled?'disabled':'')+'>'+next+'</button></div>';}
function showSteps(){document.querySelector('.steps').hidden=!!access||mode==='contact';document.querySelector('.steps').innerHTML=['Servicio','Profesional','Horario','Tus datos'].map((l,i)=>'<div class="step '+(i<=step?'active':'')+'" '+(i===step?'aria-current="step"':'')+'><span class="circle">'+(i<step?'✓':i+1)+'</span>'+l+'</div>').join('');}
function selectMode(next){slotsVersion++;mode=next;step=0;access='';appointment=null;location.hash='';requestToken=freshToken();render();}
$('newReservation').onclick=()=>selectMode('booking');$('contactReception').onclick=()=>selectMode('contact');
function render(){showSteps();
 if(mode==='contact'){contactForm();return;}
 if(step===0){content.innerHTML='<h2>¿Qué necesitas?</h2><p class="sub">Selecciona el servicio para tu próxima visita.</p><div class="choices">'+data.services.map((s,i)=>'<button class="choice" data-service="'+i+'"><span><strong>'+esc(s.label)+'</strong><small>'+s.durationMinutes+' minutos</small></span><span class="price">'+(s.priceEur!=null?money(s.priceEur):'Consultar')+'</span></button>').join('')+'</div>'+(!data.services.length?'<p>Contacta con recepción para consultar los servicios.</p>':'')+footer();document.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>{service=data.services[+b.dataset.service];professional=null;slot=null;step=1;render();});}
 if(step===1){const ps=data.professionals.filter(p=>p.serviceIds.includes(service.id));content.innerHTML='<h2>¿Con quién te gustaría?</h2><p class="sub">'+esc(service.label)+'</p><div class="choices">'+ps.map((p,i)=>'<button class="choice" data-prof="'+i+'"><strong>'+esc(p.name)+'</strong><span>→</span></button>').join('')+'</div>'+(ps.length?'':'<p>No hay profesionales disponibles. Puedes solicitar que recepción te contacte.</p>')+'<button class="back" id="back">← Volver</button>'+footer();document.querySelectorAll('[data-prof]').forEach(b=>b.onclick=()=>{professional=ps[+b.dataset.prof];slot=null;mode='booking';step=2;render();});}
 if(step===2){slotPicker(false);}
 if(step===3){detailsForm();}
 const back=$('back');if(back&&step<2)back.onclick=()=>{step=Math.max(0,step-1);slotsVersion++;render();};
}
function slotPicker(changing){
 content.innerHTML='<h2>'+ (changing?'Cambiar mi cita':'Encuentra tu momento')+'</h2><p class="sub">Horarios disponibles en '+esc(data.timezone)+'.</p>'+summary()+'<label for="date">Día</label><input id="date" type="date" min="'+today+'" max="'+maxDate+'" value="'+day+'"><div class="times" id="times" style="margin-top:18px" aria-live="polite"></div>'+buttons(changing?'Revisar cambio':'Continuar',true)+(changing?'':'<p>¿No te encaja ninguna hora?</p><button class="back" id="waitlist">Avísame si queda un hueco</button>')+footer();
 const loadSlots=async()=>{const version=++slotsVersion;slot=null;$('next').disabled=true;$('times').textContent='Buscando horarios…';try{const d=await api('slots?'+new URLSearchParams({serviceId:service.id,professionalId:professional.id,date:day}));if(version!==slotsVersion)return;$('times').innerHTML=d.slots.length?d.slots.map((s,i)=>'<button class="time" data-slot="'+i+'">'+esc(s.label)+'</button>').join(''):'<p>No quedan horas disponibles este día. Prueba otra fecha'+(changing?'.':' o apúntate a la lista de espera.')+'</p>';document.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{slot=d.slots[+b.dataset.slot];document.querySelectorAll('[data-slot]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});$('next').disabled=false;});}catch(e){if(version===slotsVersion){$('times').textContent='No se pudieron cargar los horarios.';error(e.message);}}};
 $('date').onchange=()=>{day=$('date').value;loadSlots();};$('next').onclick=()=>{if(!slot)return;if(changing){changeReview();}else{step=3;mode='booking';render();}};
 if($('waitlist'))$('waitlist').onclick=()=>{slotsVersion++;slot=null;mode='waitlist';step=3;requestToken=freshToken();render();};
 $('back').onclick=()=>{slotsVersion++;if(changing)showAppointment();else{step=1;render();}};loadSlots();
}
function personFields(){return '<label for="name">Nombre y apellidos</label><input id="name" name="name" type="text" required minlength="2" maxlength="80" autocomplete="name" value="'+esc(formValues.name)+'"><label for="phone">Teléfono con prefijo internacional</label><input id="phone" name="phone" type="tel" required maxlength="22" placeholder="+34 612 345 678" autocomplete="tel" value="'+esc(formValues.phone)+'">';}
function remember(){formValues={name:$('name').value,phone:$('phone').value};}
function detailsForm(){const wait=mode==='waitlist';content.innerHTML='<h2>'+(wait?'Avísame si queda un hueco':'Revisa y reserva')+'</h2><p class="sub">'+(wait?'Guardaremos tus preferencias para cuando se libere una cita.':'Tu cita se guardará en la agenda de la clínica.')+'</p>'+summary()+'<form id="details"><fieldset style="border:0;padding:0;margin:0">'+personFields()+(wait?'<label>Desde<input name="fromDate" type="date" min="'+today+'" max="'+maxDate+'" value="'+day+'" required></label><label>Hasta<input name="toDate" type="date" min="'+today+'" max="'+maxDate+'" value="'+day+'" required></label><label>Preferencia<select name="preferredTimeOfDay"><option value="">Cualquier hora</option><option value="MORNING">Mañana</option><option value="AFTERNOON">Tarde</option></select></label>':'')+'<p class="sub">Usaremos estos datos para gestionar esta solicitud. No incluyas información médica.</p><div class="actions"><button type="button" class="back" id="back">← Volver</button><button class="primary" type="submit">'+(wait?'Apuntarme':'Reservar cita')+'</button></div></fieldset></form>'+footer();
 $('details').onsubmit=async e=>{e.preventDefault();remember();const values=Object.fromEntries(new FormData(e.target));const body={...formValues,serviceId:service.id,professionalId:professional.id,...(wait?{fromDate:values.fromDate,toDate:values.toDate,...(values.preferredTimeOfDay?{preferredTimeOfDay:values.preferredTimeOfDay}:{})}:{startsAt:slot.iso})};const fieldset=e.target.querySelector('fieldset');fieldset.disabled=true;try{await api(wait?'waitlist':'book',body,requestToken);if(wait){content.innerHTML='<div class="success"><div class="success-icon">✓</div><h2>Ya estás en la lista</h2><p>Tu preferencia está guardada. Recepción podrá contactarte si hay una cita compatible. Esto todavía no es una reserva.</p><button class="primary" id="again">Volver a reservas</button></div>';$('again').onclick=()=>selectMode('booking');}else{access=requestToken;location.hash=access;await showAppointment(true);}}catch(err){error(err.message);fieldset.disabled=false;}};
 $('back').onclick=()=>{remember();step=2;mode='booking';render();};
}
async function showAppointment(created=false){showSteps();content.innerHTML='<p>Cargando tu cita…</p>'+footer();try{appointment=await api('appointment',undefined,access);content.innerHTML='<h2>'+(created?'Tu cita está guardada':'Tu cita')+'</h2><p class="sub">'+esc(appointment.statusLabel)+'</p><div class="summary"><strong>'+esc(appointment.serviceLabel)+'</strong><br>'+esc(appointment.professionalName)+'<br>'+esc(appointment.when)+'</div>'+(appointment.editable?'<div class="actions">'+(appointment.status==='PENDING_CONFIRMATION'?'<button class="primary" id="confirm">Confirmar asistencia</button>':'')+'<button class="primary" id="change">Cambiar cita</button><button class="back" id="cancel">Cancelar cita</button></div>':'<p>Para más información, contacta con recepción.</p>')+'<label for="privateLink">Tu enlace privado para gestionar esta cita</label><input id="privateLink" type="text" readonly value="'+esc(location.origin+'/reservar#'+access)+'"><button class="back" id="copyLink">Copiar enlace</button><p class="sub">Guárdalo. Quien tenga este enlace puede gestionar esta cita. Caduca a los 90 días.</p>'+footer();
 $('copyLink').onclick=async()=>{try{await navigator.clipboard.writeText($('privateLink').value);$('copyLink').textContent='Enlace copiado';}catch{$('privateLink').select();error('Selecciona y copia el enlace.');}};
 if($('confirm'))$('confirm').onclick=()=>runManage({action:'confirm'});
 if($('change'))$('change').onclick=()=>{service={id:appointment.serviceId,label:appointment.serviceLabel};professional={id:appointment.professionalId,name:appointment.professionalName};day=today;slot=null;slotPicker(true);};
 if($('cancel'))$('cancel').onclick=()=>{content.innerHTML='<h2>¿Cancelar esta cita?</h2><p>Se liberará el horario de '+esc(appointment.when)+'.</p><div class="actions"><button class="back" id="keep">Conservar mi cita</button><button class="primary" id="doCancel">Sí, cancelar</button></div>'+footer();$('keep').onclick=()=>showAppointment();$('doCancel').onclick=()=>runManage({action:'cancel'});};
 }catch(e){content.innerHTML='<h2>No podemos abrir esta cita</h2><p>'+esc(e.message)+'</p><p>Puedes solicitar ayuda con «Hablar con recepción».</p>';}}
function changeReview(){content.innerHTML='<h2>Revisa el nuevo horario</h2>'+summary()+'<p>La cita anterior se conserva hasta que el nuevo horario quede reservado.</p><div class="actions"><button class="back" id="keep">Volver</button><button class="primary" id="doChange">Confirmar cambio</button></div>'+footer();$('keep').onclick=()=>slotPicker(true);$('doChange').onclick=()=>runManage({action:'change',startsAt:slot.iso});}
async function runManage(body){const buttons=Array.from(content.querySelectorAll('button'));buttons.forEach(b=>b.disabled=true);try{await api('manage',body,access);await showAppointment();}catch(e){error(e.message);buttons.forEach(b=>b.disabled=false);}}
function contactForm(){content.innerHTML='<h2>Hablar con recepción</h2><p class="sub">Deja tu teléfono y el equipo revisará tu solicitud en horario de atención. No es un chat en directo.</p><form id="contact"><fieldset style="border:0;padding:0;margin:0">'+personFields()+'<label for="message">¿En qué podemos ayudarte?</label><textarea id="message" name="message" required minlength="3" maxlength="500" rows="3" placeholder="Por ejemplo: necesito ayuda para elegir un servicio. No incluyas datos médicos."></textarea><button class="primary" type="submit" style="margin-top:18px">Pedir que me contacten</button></fieldset></form>'+footer();$('contact').onsubmit=async e=>{e.preventDefault();remember();const fieldset=e.target.querySelector('fieldset');fieldset.disabled=true;try{await api('contact',{...formValues,message:$('message').value});content.innerHTML='<div class="success"><div class="success-icon">✓</div><h2>Solicitud recibida</h2><p>El equipo tiene tu solicitud y tu teléfono para ponerse en contacto contigo.</p><button class="primary" id="again">Volver a reservas</button></div>';$('again').onclick=()=>selectMode('booking');}catch(err){error(err.message);fieldset.disabled=false;}};}
const fragment=location.hash.slice(1);if(/^[a-f0-9]{64}$/.test(fragment)){access=fragment;showAppointment();}else render();
`;
